sudo: false
language: node_js
node_js:
  - '5'
cache:
  directories:
    - node_modules
before_script:
  - npm prune
notifications:
  email: false
script:
  - npm run validate
after_success:
  - npm run report-coverage && npm run semantic-release
branches:
  only:
    - master
